/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.AppliancesInfo;


import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author Lenovo-i5
 */
public class AppliancesInfo extends javax.swing.JFrame {

    /**
     * Creates new form AppliancesInfo
     */
    
    private ArrayList <FruitInventoryData> list = new ArrayList();
     
    
    public AppliancesInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        btngroupTypes = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableInfo = new javax.swing.JTable();
        panalFruitDetails = new javax.swing.JPanel();
        btnMedium = new javax.swing.JRadioButton();
        lblRange = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnLow = new javax.swing.JRadioButton();
        seasoncmbbox = new javax.swing.JComboBox<>();
        txtName = new javax.swing.JTextField();
        btnHigh = new javax.swing.JRadioButton();
        lblFruitID = new javax.swing.JLabel();
        txtFruitID = new javax.swing.JTextField();
        lblTTypes = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        panelButtons = new javax.swing.JPanel();
        btnadd = new javax.swing.JButton();
        btnclearTextField = new javax.swing.JButton();
        btnClearTable = new javax.swing.JButton();
        txtDate = new com.toedter.calendar.JDateChooser();
        panelSearch = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        lblprice = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        lbltypes = new javax.swing.JLabel();
        btnTypesSearch = new javax.swing.JButton();
        cmbTypes = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        picture1 = new javax.swing.JLabel();
        picture2 = new javax.swing.JLabel();
        picture3 = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        itemSave = new javax.swing.JMenuItem();
        menuitemOpen = new javax.swing.JMenuItem();
        menuItemImport = new javax.swing.JMenuItem();
        menuitemExit = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        ItemAbout = new javax.swing.JMenuItem();
        menuItemHelp = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fruit Inventory System");
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1800, 970));
        setResizable(false);

        TableInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TableInfo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "FruitID", "Date", "Fruit Name", "Range", "Types", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableInfo);

        panalFruitDetails.setBackground(new java.awt.Color(102, 102, 255));
        panalFruitDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fruits Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        btngroupTypes.add(btnMedium);
        btnMedium.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMedium.setText("Medium");
        btnMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediumActionPerformed(evt);
            }
        });

        lblRange.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblRange.setText("Range");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Price");

        txtQuantity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQuantityMouseClicked(evt);
            }
        });
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        btngroupTypes.add(btnLow);
        btnLow.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLow.setSelected(true);
        btnLow.setText("Low");

        seasoncmbbox.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        seasoncmbbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Local Fruit", "Common Fruit", "Exortic Fruit", "Citrus Fruit", "Berries" }));

        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNameMouseClicked(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        btngroupTypes.add(btnHigh);
        btnHigh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnHigh.setText("High");
        btnHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHighActionPerformed(evt);
            }
        });

        lblFruitID.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblFruitID.setText("FruitID");

        txtFruitID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFruitIDMouseClicked(evt);
            }
        });

        lblTTypes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTTypes.setText("Types");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblName.setText("Fruit Name");

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDate.setText("Date");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Quantity(KG)");

        txtPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPriceMouseClicked(evt);
            }
        });

        panelButtons.setBackground(new java.awt.Color(102, 102, 255));
        panelButtons.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buttons", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        btnadd.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnadd.setText("ADD To Tables");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnclearTextField.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnclearTextField.setText("Clear TextField");
        btnclearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearTextFieldActionPerformed(evt);
            }
        });

        btnClearTable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnClearTable.setText("Clear Table");
        btnClearTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonsLayout = new javax.swing.GroupLayout(panelButtons);
        panelButtons.setLayout(panelButtonsLayout);
        panelButtonsLayout.setHorizontalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelButtonsLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelButtonsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnclearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnClearTable, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panelButtonsLayout.setVerticalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addComponent(btnadd, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnclearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearTable, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        txtDate.setDateFormatString("YYYY-MM-DD");

        javax.swing.GroupLayout panalFruitDetailsLayout = new javax.swing.GroupLayout(panalFruitDetails);
        panalFruitDetails.setLayout(panalFruitDetailsLayout);
        panalFruitDetailsLayout.setHorizontalGroup(
            panalFruitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panalFruitDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panalFruitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panalFruitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panalFruitDetailsLayout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panalFruitDetailsLayout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panalFruitDetailsLayout.createSequentialGroup()
                        .addGroup(panalFruitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFruitID, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panalFruitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panalFruitDetailsLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(txtFruitID, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panalFruitDetailsLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panalFruitDetailsLayout.createSequentialGroup()
                        .addGroup(panalFruitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panalFruitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblRange, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                .addComponent(lblTTypes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panalFruitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panalFruitDetailsLayout.createSequentialGroup()
                                .addComponent(btnLow, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panalFruitDetailsLayout.createSequentialGroup()
                                .addComponent(seasoncmbbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(28, 28, 28))
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        panalFruitDetailsLayout.setVerticalGroup(
            panalFruitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panalFruitDetailsLayout.createSequentialGroup()
                .addGroup(panalFruitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFruitID, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(lblFruitID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(panalFruitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panalFruitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panalFruitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRange, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLow, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panalFruitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panalFruitDetailsLayout.createSequentialGroup()
                        .addComponent(seasoncmbbox, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(33, 33, 33)
                .addGroup(panalFruitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panalFruitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelSearch.setBackground(new java.awt.Color(102, 102, 255));
        panelSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        lblprice.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblprice.setText("Search by Price of Fruits:");

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lbltypes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbltypes.setText("Search by Types Fruits:");

        btnTypesSearch.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnTypesSearch.setText("Search");
        btnTypesSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTypesSearchActionPerformed(evt);
            }
        });

        cmbTypes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cmbTypes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Local Fruit", "Common Fruit", "Exortic Fruit", "Citrus Fruit", "Berries" }));

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTypesSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblprice, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(lbltypes, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprice, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltypes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTypesSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel1.setMaximumSize(new java.awt.Dimension(1617, 970));

        picture1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/AppliancesInfo/Pictures/1.jpg"))); // NOI18N

        picture2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/AppliancesInfo/Pictures/3.jpg"))); // NOI18N

        picture3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/AppliancesInfo/Pictures/3.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(picture1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(picture2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(picture3, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(picture1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(picture2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(picture3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Title1.setBackground(new java.awt.Color(153, 51, 255));
        Title1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/AppliancesInfo/Pictures/4.PNG"))); // NOI18N

        menuFile.setForeground(new java.awt.Color(0, 204, 204));
        menuFile.setText("File");

        itemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        itemSave.setText("Save");
        itemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSaveActionPerformed(evt);
            }
        });
        menuFile.add(itemSave);

        menuitemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuitemOpen.setText("Open");
        menuitemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemOpenActionPerformed(evt);
            }
        });
        menuFile.add(menuitemOpen);

        menuItemImport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menuItemImport.setText("Import");
        menuItemImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemImportActionPerformed(evt);
            }
        });
        menuFile.add(menuItemImport);

        menuitemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuitemExit.setText("Exit");
        menuitemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemExitActionPerformed(evt);
            }
        });
        menuFile.add(menuitemExit);

        jMenuBar1.add(menuFile);

        menuHelp.setForeground(new java.awt.Color(0, 204, 204));
        menuHelp.setText("Help");
        menuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelpActionPerformed(evt);
            }
        });

        ItemAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        ItemAbout.setText("About");
        ItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAboutActionPerformed(evt);
            }
        });
        menuHelp.add(ItemAbout);

        menuItemHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        menuItemHelp.setText("Help");
        menuItemHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHelpActionPerformed(evt);
            }
        });
        menuHelp.add(menuItemHelp);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Title1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panalFruitDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)))
                        .addGap(750, 750, 750))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(868, 868, 868)
                        .addComponent(jLabel3)
                        .addGap(820, 820, 820))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panalFruitDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMediumActionPerformed

    private void menuitemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuitemExitActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if(txtSearch.getText().trim().isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "OOPS!!!\nSeems like you left the input-box empty\n Please Fill all the input area ", "Empty Box", 0);
        }else{
            
            try{
                
                 sort(list);
                 String pricesearch = txtSearch.getText().trim();
                 int searchvalue = Integer.parseInt(pricesearch);
                 int index = binarySearch(list,0,list.size()-1,searchvalue);
                 if (index == -1){
                     JOptionPane.showMessageDialog(rootPane, "OOPS!!!\n Seems there is not any details with the price of "+" "+searchvalue,"Price not Found",JOptionPane.ERROR_MESSAGE);
                 }else{
                     JOptionPane.showMessageDialog(rootPane,"The Detils of Serched Price = " +" "+ searchvalue+"\n The Fruit ID = "+" "+list.get(index).getFruitID()
                             +"\n The Date of Fruit Import = "+" "+list.get(index).getDate()+"\n The Fruit Name = "+" "+
                             list.get(index).getName()+"\n The Types of Fruit = " + " "+list.get(index).getTypes()+"\n The Price Range of Fruit = "+" "+list.get(index).getRange()
                             +"\n The Quantity of Frut = "+list.get(index).getQuantity()+"\n The Price of Fruit = "+" "+list.get(index).getPrice(),"Result",JOptionPane.INFORMATION_MESSAGE);
                 }
                 
                
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane, "OOPS!!!\nSeems like the format didn't match.\n Please put in integer in search textfield", "Format Mismatch", 0);
            }
            
        } 
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String FruitID = txtFruitID.getText();
        String Date = ((JTextField) txtDate.getDateEditor().getUiComponent()).getText();
        String Name = txtName.getText();
        String Price = txtPrice.getText();
        String Quantity = txtQuantity.getText();
        
        String Range = null;
        if (btnLow.isSelected()) {
        Range = "Low";
        }
        else if (btnMedium.isSelected()) {
        Range = "Medium";
        }
        
        else{
            Range = "High";
        }
        
        String Types = seasoncmbbox.getSelectedItem().toString();
        
           
        
        // Validation
        if (FruitID.trim().equals("") || Name.trim().equals("") || Date.trim().equals("") || Price.trim().equals("") || Range.trim().equals("") || Types.trim().equals("") || Quantity.trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "OOPS!!!\nSeems like you left the input-box empty\n Please Fill all the input area ", "Empty Box", 0);

            return;

        } else {
            for (FruitInventoryData data : list) {
                if (FruitID.equals(data.getFruitID())) {
                    JOptionPane.showMessageDialog(rootPane, "OOPS!!!\nSeems like you put the same FruitID\n Please put diffrent id because id should be always unique ", "Error", 0);
                    return;
                    

                }

            }
             try {
                        int fruitID;
                        int price;
                        int quantity;

                        fruitID = Integer.parseInt(FruitID);
                        price = Integer.parseInt(Price);
                        quantity = Integer.parseInt(Quantity);

                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(rootPane, "OOPS!!!\nSeems like the format didn't match.\n Please put in integer in FruitID, Price, Quantity", "Format Mismatch", 0);
                        return;
                    }
        }

        int rowCount = TableInfo.getRowCount();
        int nextRow = 0;
        boolean emptyRowflag = false;
        String data;
        do {
            data = (String) TableInfo.getValueAt(nextRow, 0);
            if (data != null && data.length() != 0) {
                nextRow++;

            } else {
                emptyRowflag = true;
            }

        } while (nextRow < rowCount && !emptyRowflag);

        if (nextRow < rowCount) {
            String[] value = {FruitID, Date, Name, Range, Types, Quantity, Price};
            list.add(new FruitInventoryData(FruitID, Date, Name, Range, Types, Quantity, Price));

            int colcount = TableInfo.getColumnCount();
            for (int i = 0; i < colcount; i++) {
                TableInfo.setValueAt(value[i], nextRow, i);

            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "OOPS!!!\n You cannot add More values", "Error", 0);
        }


    }//GEN-LAST:event_btnaddActionPerformed
  
    private static int binarySearch(ArrayList<FruitInventoryData> sortedlist, int Low, int High, int pricevalue){
      
        if (Low <= High ){
            int Mid = (High+Low)/2;
            int Midvalue = Integer.parseInt(sortedlist.get(Mid).getPrice());
            
           if (Midvalue == pricevalue){
            return Mid;
        }
           else if (Midvalue < pricevalue){
               return binarySearch(sortedlist,Mid+1,High,pricevalue);
           }else{
               return binarySearch(sortedlist ,Low,Mid-1,pricevalue);
           }
        }
        else{
            return -1;
        }
    }
    
    private static void sort(ArrayList<FruitInventoryData> Unsortedlist){
        
        if (Unsortedlist.size()<=1){
            return;
        }
        int n = Unsortedlist.size()/2;
        int m = Unsortedlist.size()-n;
        ArrayList<FruitInventoryData> First = new ArrayList();
        ArrayList<FruitInventoryData> Second = new ArrayList();
        for (int i = 0; i<n; i++){
            First.add(Unsortedlist.get(i));
        }
        for (int i = 0; i<m; i++){
            Second.add(Unsortedlist.get(First.size()+i));
        }
        sort(First);
        sort(Second);
        merge(First,Second,Unsortedlist);
    }
    
    private static void merge(ArrayList<FruitInventoryData> First, ArrayList<FruitInventoryData> Second, ArrayList<FruitInventoryData> Unsortedlist){
        int iFirst = 0;
        int iSecond = 0;
        int j = 0;
        while(iFirst < First.size() && iSecond < Second.size()){
            if( Integer.parseInt(First.get(iFirst).getPrice()) < Integer.parseInt(Second.get(iSecond).getPrice())){
                Unsortedlist.set(j,First.get(iFirst));
                iFirst++;
            } else{
                Unsortedlist.set(j,Second.get(iSecond));
                iSecond++;
            }
            j++;
        }
        while(iFirst < First.size()){
            Unsortedlist.set(j,First.get(iFirst));
            iFirst++;
            j++;
        }
        while(iSecond < Second.size()){
            Unsortedlist.set(j,Second.get(iSecond));
            iSecond++;
            j++;
        }
    }
   
    private void txtFruitIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFruitIDMouseClicked
        // TODO add your handling code here:
        txtFruitID.setText("");
    }//GEN-LAST:event_txtFruitIDMouseClicked

    private void txtNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseClicked
        // TODO add your handling code here:
        txtName.setText("");
    }//GEN-LAST:event_txtNameMouseClicked

    private void txtQuantityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuantityMouseClicked
        // TODO add your handling code here:
        txtQuantity.setText("");
    }//GEN-LAST:event_txtQuantityMouseClicked

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        // TODO add your handling code here:
        txtSearch.setText("");
    }//GEN-LAST:event_txtSearchMouseClicked

    private void btnclearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearTextFieldActionPerformed
        // TODO add your handling code here:
        txtFruitID.setText("");
        txtDate.setCalendar(null);
        txtName.setText("");
        txtQuantity.setText("");
        txtSearch.setText("");
        txtPrice.setText("");
        
        
    }//GEN-LAST:event_btnclearTextFieldActionPerformed

    private void txtPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPriceMouseClicked
        // TODO add your handling code here:
        txtPrice.setText("");
    }//GEN-LAST:event_txtPriceMouseClicked

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void txtDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDateMouseClicked
        // TODO add your handling code here:
       txtDate.setCalendar(null);
    }//GEN-LAST:event_txtDateMouseClicked

    private void itemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSaveActionPerformed
        // TODO add your handling code here:
        try{
            File file = new File("..\\Appliances_IS\\FruitInventory\\FruitInventory.csv");
            if(!file.isFile()){
                file.createNewFile();
            }
            FileWriter fw = new FileWriter(file);
            for( FruitInventoryData data:list){
                String value[]= {data.getFruitID(),data.getDate(),data.getName(),data.getRange(),data.getTypes(),data.getQuantity(),data.getPrice()};
                for (int i=0; i<value.length; i++){
                fw.append(value[i]);
                if( i == value.length-1){
                    break;
                }
                fw.append(",");
            }
                fw.append("\n");
            }
            fw.flush();
            fw.close();
            
            JOptionPane.showMessageDialog(rootPane, "Congratulation Save Sucess", "Save Sucess", 1);
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(rootPane, "OOPS!!!\n Seems Like problem in saving File", "Error", 0);
        }
     
    }//GEN-LAST:event_itemSaveActionPerformed

    private void btnClearTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearTableActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < TableInfo.getRowCount(); i++) {
        for(int j = 0; j < TableInfo.getColumnCount(); j++) {
        TableInfo.setValueAt("", i, j);
            }
        }
    }//GEN-LAST:event_btnClearTableActionPerformed

    private void menuitemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemOpenActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("");
            int userSelection = fileChooser.showOpenDialog(this); 
            if (userSelection == JFileChooser.APPROVE_OPTION) {
                File fileToOpen = fileChooser.getSelectedFile();

                Runtime.getRuntime().exec(" rundll32 url.dll, FileProtocolHandler " + fileToOpen);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "OOPS!!!\n Seems like there is Problem in opening the file", "Error", 0);

        }
    }//GEN-LAST:event_menuitemOpenActionPerformed

    private void menuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelpActionPerformed
        // TODO add your handling code here:    
    }//GEN-LAST:event_menuHelpActionPerformed

    private void ItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, ""
        + "\n              Fruit Inventory System"
        + "\n              V1.0 "
        + "\n              Developed By:"
        + "\n              Hemaraj Dhakal"
        + "\n              Sahikshya Basnet"
        + "\n              Rohit Gurung"
        + "\n              Autsav Adhikari"       
        + "\n              Second Year Student of Itahari International College "
        + "\n              Thank You!!!",
          "About",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ItemAboutActionPerformed

    private void menuItemImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemImportActionPerformed
        // TODO add your handling code here:
       try{
           BufferedReader BR = new BufferedReader(new FileReader("..\\Appliances_IS\\FruitInventory\\FruitInventory.csv"));
           String row ="";
           while((row = BR.readLine()) != null){
               String[] value = row.split(",");
               int rowCount = TableInfo.getRowCount();
               int nextRow = 0;
               boolean emptyRowflag = false;
               String data;
               do {
                   data = (String) TableInfo.getValueAt(nextRow, 0);
                   if (data != null && data.length() != 0) {
                       nextRow++;

                   } else {
                       emptyRowflag = true;
                   }

               } while (nextRow < rowCount && !emptyRowflag);

               if (nextRow < rowCount) {
                   FruitInventoryData rows = new FruitInventoryData(value[0], value[1], value[2], value[3], value[4], value[5], value[6]);
                   list.add(rows);
                
                   int colcount = TableInfo.getColumnCount();
                   for (int i = 0; i < colcount; i++) {
                       TableInfo.setValueAt(value[i], nextRow, i);

                   }
                   
               }
           }
                   
       }catch(FileNotFoundException e){
          JOptionPane.showMessageDialog(rootPane, "OOPS!!!\n Seems like File not Found", "Error", 0);
       }catch(IOException e){
          JOptionPane.showMessageDialog(rootPane, "OOPS!!!\n Seems like problem in importing file", "Error", 0);
       }catch (ArrayIndexOutOfBoundsException e) {
           
       }
        JOptionPane.showMessageDialog(rootPane, "Import Sucessfull", "Information", 1);
        
    }//GEN-LAST:event_menuItemImportActionPerformed

    private void btnTypesSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTypesSearchActionPerformed
        // TODO add your handling code here:
        String availableTypes = "";
        int typeCount = 0;
        int listIndex = 0;
        try{
            if( list.size()> 0){
                while(listIndex < list.size()){
                    if(cmbTypes.getSelectedItem().toString().equals(list.get(listIndex).getTypes())){
                        availableTypes += list.get(listIndex).getName()+"\n";
                        typeCount ++;
                    }
                    listIndex++;
                }
                if(typeCount == 0){
                    JOptionPane.showMessageDialog(rootPane,"OOPS!!!\n Seems Like "+" "+cmbTypes.getSelectedItem().toString().trim()+" "+"Fuit Types is not Available"," Fruit Types Not found" ,JOptionPane.ERROR_MESSAGE);
                    return;
                }
                JOptionPane.showMessageDialog(rootPane,"The" +" "+typeCount+" "+"Available Fruit Types Deatils is:"+"\n"+cmbTypes.getSelectedItem()+" "+"Fruit Types"+" "+"Named: " +" "+availableTypes.toUpperCase()," Fruit Types Found",JOptionPane.INFORMATION_MESSAGE);
            }
            
        }catch(IndexOutOfBoundsException e){
             JOptionPane.showMessageDialog(rootPane, "OOPS!!!\n Seems Like Problem in Searching Fruit Types","Types Result",JOptionPane.INFORMATION_MESSAGE);
             
        }
        
    }//GEN-LAST:event_btnTypesSearchActionPerformed

    private void menuItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHelpActionPerformed
        // TODO add your handling code here:
        try{
            Runtime.getRuntime().exec(" rundll32 url.dll, FileProtocolHandler " + "C:\\Users\\Lenovo-i5\\Documents\\NetBeansProjects\\Appliances_IS\\FruitInventory\\User Manual.pdf");
         
        }catch(IOException e){
                 JOptionPane.showMessageDialog(rootPane, "OOPS!!!\n Seems Like Problem in searching the file","Error",0);
                
                } 
    }//GEN-LAST:event_menuItemHelpActionPerformed

    private void btnHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHighActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHighActionPerformed
       
    

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppliancesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppliancesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppliancesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppliancesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppliancesInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemAbout;
    private javax.swing.JTable TableInfo;
    private javax.swing.JLabel Title1;
    private javax.swing.JButton btnClearTable;
    private javax.swing.JRadioButton btnHigh;
    private javax.swing.JRadioButton btnLow;
    private javax.swing.JRadioButton btnMedium;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTypesSearch;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclearTextField;
    private javax.swing.ButtonGroup btngroupTypes;
    private javax.swing.JComboBox<String> cmbTypes;
    private javax.swing.JMenuItem itemSave;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFruitID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRange;
    private javax.swing.JLabel lblTTypes;
    private javax.swing.JLabel lblprice;
    private javax.swing.JLabel lbltypes;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemHelp;
    private javax.swing.JMenuItem menuItemImport;
    private javax.swing.JMenuItem menuitemExit;
    private javax.swing.JMenuItem menuitemOpen;
    private javax.swing.JPanel panalFruitDetails;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JLabel picture1;
    private javax.swing.JLabel picture2;
    private javax.swing.JLabel picture3;
    private javax.swing.JComboBox<String> seasoncmbbox;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtFruitID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    
}
